using System;
using System.Windows.Forms;
using DevExpress.XtraBars.Navigation;
using AVM.UI;

namespace AVM.UI
{
    public partial class AdminForm : DevExpress.XtraEditors.XtraForm
    {
        // Only declare NEW fields not in Designer
        private AccordionControlElement accServiceRequests; 
        private AccordionControlElement accLeaveRequests; 

        public AdminForm()
        {
            InitializeComponent();
            SetupNewModules();
            BindEvents();
        }

        private void SetupNewModules()
        {
            // Create new elements
            this.accServiceRequests = new AccordionControlElement() { Text = "Gelen Talepler", Style = ElementStyle.Item };
            this.accLeaveRequests = new AccordionControlElement() { Text = "İzin Onayları", Style = ElementStyle.Item };

            // Ensure Logout is at the bottom
            if(this.accordionControl1.Elements.Contains(accCikisYap))
            {
                this.accordionControl1.Elements.Remove(accCikisYap);
            }

            // Adding to the main collection
            this.accordionControl1.Elements.Add(accServiceRequests);
            this.accordionControl1.Elements.Add(accLeaveRequests);
            
            // Add Logout back at the end
            this.accordionControl1.Elements.Add(accCikisYap);
        }

        private void BindEvents()
        {
            // Existing Elements (from Designer)
            accAnaSayfa.Click += (s, e) => LoadModule(new UCAnaSayfa());
            accMagazalar.Click += (s, e) => LoadModule(new UCMagazalar());
            accKiracilar.Click += (s, e) => LoadModule(new UCKiracilar());
            accKiraOdemeleri.Click += (s, e) => LoadModule(new UCRentManagement());
            accGiderler.Click += (s, e) => LoadModule(new UCExpenses());
            accPersoneller.Click += (s, e) => LoadModule(new UCPersonnel());
            accDuyuruMesaj.Click += (s, e) => LoadModule(new UCAnnouncements());
            
            // New Elements
            accServiceRequests.Click += (s, e) => LoadModule(new UCAdminServiceRequests());
            accLeaveRequests.Click += (s, e) => LoadModule(new UCAdminLeaveRequests());

            accCikisYap.Click += (s, e) => this.Close();

            // Default Load
            LoadModule(new UCAnaSayfa());
        }

        private void LoadModule(UserControl module)
        {
            panelMain.Controls.Clear();
            module.Dock = DockStyle.Fill;
            panelMain.Controls.Add(module);
        }

        private void AdminForm_Load(object sender, EventArgs e)
        {
            // Already handled in Constructor, but can be used for other init
        }

        // Event handlers generated by designer that might be linked in Designer.cs
        // We keep them to avoid errors if Designer references them.
        private void accAnaSayfa_Click_1(object sender, EventArgs e) => LoadModule(new UCAnaSayfa());
        private void accMagazalar_Click(object sender, EventArgs e) => LoadModule(new UCMagazalar());
        private void accKiracilar_Click(object sender, EventArgs e) => LoadModule(new UCKiracilar());
        private void accKiraOdemeleri_Click(object sender, EventArgs e) => LoadModule(new UCRentManagement());
    }
}
